//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderView
    {
        public int idOrder { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public string Brigade { get; set; }
        public string Service { get; set; }
        public string ServiceCost { get; set; }
        public string Material { get; set; }
        public string MaterialCost { get; set; }
        public Nullable<int> SUM { get; set; }
        public string Date { get; set; }
    }
}
