//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseMaterial
    {
        public int idOrder { get; set; }
        public int idMaterial { get; set; }
        public int Quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
    }
}
