//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unit_TestAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerView
    {
        public int idWorker { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Telephone { get; set; }
        public string Expr1 { get; set; }
    }
}
