//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionCompany.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkersBrigade
    {
        public int idBrigade { get; set; }
        public int idWorker { get; set; }
        public string @null { get; set; }
    
        public virtual Brigade Brigade { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
